version: "3.8"

services:
  api-gateway:
    container_name: api-gateway
    image: 676206906655.dkr.ecr.ap-southeast-1.amazonaws.com/fintech_web_app:api-gateway-latest
    expose:
      - "3000"   # chỉ expose nội bộ cho nginx, không public ra ngoài
    depends_on:
      - auth-service
      - charge-service
      - transaction-service
      - history-service
    env_file:
      - .env.docker
    networks:
      - app-network

  auth-service:
    container_name: auth-service
    image: 676206906655.dkr.ecr.ap-southeast-1.amazonaws.com/fintech_web_app:auth-service-latest
    ports:
      - "3001:3001"
    env_file:
      - .env.docker
    networks:
      - app-network

  charge-service:
    container_name: charge-service
    image: 676206906655.dkr.ecr.ap-southeast-1.amazonaws.com/fintech_web_app:charge-service-latest
    ports:
      - "3002:3002"
    env_file:
      - .env.docker
    networks:
      - app-network

  history-service:
    container_name: history-service
    image: 676206906655.dkr.ecr.ap-southeast-1.amazonaws.com/fintech_web_app:history-service-latest
    ports:
      - "3003:3003"
    env_file:
      - .env.docker
    networks:
      - app-network

  transaction-service:
    container_name: transaction-service
    image: 676206906655.dkr.ecr.ap-southeast-1.amazonaws.com/fintech_web_app:transaction-service-latest
    ports:
      - "3004:3004"
    env_file:
      - .env.docker
    networks:
      - app-network

  nginx_proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - api-gateway
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
